---
output: github_document
bibliography: doc/breast_cancer_refs.bib
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Identifying strong predictors of breast cancer recurrence

Group Members: 
Haoyu(Clara) Su, Fanli Zhou, Ke Xin(Margaret) Zhao




The breast cancer data set was obtained from the UCI Machine Learning Repository [@Dua2019] and can be found [here](https://archive.ics.uci.edu/ml/datasets/Breast+Cancer). The data set looks at the recurrence and non-recurrence of breast cancer based on 9 features, including groups of age, menopause time, tumor size, ranges of the number of axillary lymph nodes, presence of node in cap, degree of malignancy, breast type, breast quadrant, and whether the patient used radiation therapy. The data set contains 286 instances with missing values. 

## Report

The final report can be found [here]()

## Usage


## Dependencies

- Python 3.7.4 and Python packages:
    + pandas==0.25.2
    + numpy==1.17.2
    + altair==3.3.0
    + sklearn==0.22
    
- R 3.6.1 and R packages:
    + knitr==1.27.2 
    + tidyverse==1.3.0

# References